<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SnowShot.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SnowShot.Contracts\SnowShot.Contracts.csproj" />
    <ProjectReference Include="..\SnowShot.Application\SnowShot.Application.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>
