\set ON_ERROR_STOP on

ALTER ROLE snowshot_api NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
REVOKE CREATE, TEMPORARY ON DATABASE :"database_name" FROM snowshot_api;
REVOKE ALL ON SCHEMA snowshot FROM snowshot_api;
GRANT USAGE ON SCHEMA snowshot TO snowshot_api;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA snowshot TO snowshot_api;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA snowshot TO snowshot_api;

ALTER DEFAULT PRIVILEGES FOR ROLE snowshot_migrator IN SCHEMA snowshot
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO snowshot_api;
ALTER DEFAULT PRIVILEGES FOR ROLE snowshot_migrator IN SCHEMA snowshot
    GRANT USAGE, SELECT ON SEQUENCES TO snowshot_api;
