// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SnowShot.Infrastructure.Persistence;

#nullable disable

namespace SnowShot.Infrastructure.Production.Persistence.Migrations
{
    [DbContext(typeof(SnowShotDbContext))]
    partial class SnowShotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("snowshot")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.AllowancePeriodEntity", b =>
                {
                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PeriodDate")
                        .HasColumnType("date");

                    b.Property<long>("AppliedPolicyRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("CommittedNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("LimitNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservedNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PrincipalId", "PeriodDate");

                    b.HasIndex("PeriodDate")
                        .HasDatabaseName("ix_allowance_periods_retention");

                    b.ToTable("allowance_periods", "snowshot", t =>
                        {
                            t.HasCheckConstraint("ck_allowance_nonnegative", "\"LimitNanoYuan\" > 0 AND \"CommittedNanoYuan\" >= 0 AND \"ReservedNanoYuan\" >= 0 AND \"AppliedPolicyRevision\" > 0");
                        });
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.DailyAggregateEntity", b =>
                {
                    b.Property<DateOnly>("UsageDate")
                        .HasColumnType("date");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Resource")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("InputUnits")
                        .HasColumnType("bigint");

                    b.Property<long>("OperatorCostNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("OperatorOverageNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("OutputUnits")
                        .HasColumnType("bigint");

                    b.Property<long>("PublicCostNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("Requests")
                        .HasColumnType("bigint");

                    b.Property<long>("UnknownCostRequests")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UsageDate", "Kind", "Resource");

                    b.HasIndex("UsageDate")
                        .HasDatabaseName("ix_daily_aggregates_retention");

                    b.ToTable("daily_aggregates", "snowshot");
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.OperatorBudgetPeriodEntity", b =>
                {
                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<long>("AppliedPolicyRevision")
                        .HasColumnType("bigint");

                    b.Property<long>("CommittedNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("LimitNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservedNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Kind", "PeriodKey");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_operator_budget_periods_retention");

                    b.ToTable("operator_budget_periods", "snowshot", t =>
                        {
                            t.HasCheckConstraint("ck_operator_budget_nonnegative", "\"LimitNanoYuan\" > 0 AND \"CommittedNanoYuan\" >= 0 AND \"ReservedNanoYuan\" >= 0 AND \"AppliedPolicyRevision\" > 0");

                            t.HasCheckConstraint("ck_operator_period_kind", "\"Kind\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.PolicyRevisionEntity", b =>
                {
                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CanonicalDocument")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DailyOperatorBudgetNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<long>("MonthlyOperatorBudgetNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("PrincipalDailyAllowanceNanoYuan")
                        .HasColumnType("bigint");

                    b.HasKey("Revision");

                    b.HasIndex("Fingerprint")
                        .HasDatabaseName("ix_policy_revisions_fingerprint");

                    b.ToTable("policy_revisions", "snowshot", t =>
                        {
                            t.HasCheckConstraint("ck_policy_revision_caps", "\"PrincipalDailyAllowanceNanoYuan\" > 0 AND \"DailyOperatorBudgetNanoYuan\" > 0 AND \"MonthlyOperatorBudgetNanoYuan\" > 0");

                            t.HasCheckConstraint("ck_policy_revision_fingerprint", "octet_length(\"Fingerprint\") = 32");

                            t.HasCheckConstraint("ck_policy_revision_positive", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.PolicyStateEntity", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint");

                    b.Property<long?>("ActiveRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveRevision");

                    b.ToTable("policy_state", "snowshot", t =>
                        {
                            t.HasCheckConstraint("ck_policy_state_singleton", "\"Id\" = 1");
                        });
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.PrincipalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_principals_retention");

                    b.ToTable("principals", "snowshot");
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.PrincipalFingerprintEntity", b =>
                {
                    b.Property<byte[]>("Fingerprint")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.HasKey("Fingerprint");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_principal_fingerprints_retention");

                    b.HasIndex("PrincipalId")
                        .HasDatabaseName("ix_principal_fingerprints_principal");

                    b.ToTable("principal_fingerprints", "snowshot", t =>
                        {
                            t.HasCheckConstraint("ck_principal_fingerprint_length", "octet_length(\"Fingerprint\") = 32");
                        });
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.ProviderAttemptEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("CostKnown")
                        .HasColumnType("boolean");

                    b.Property<long>("CostNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<int>("DispatchState")
                        .HasColumnType("integer");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<long>("InputUnits")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("OutputUnits")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAt")
                        .HasDatabaseName("ix_provider_attempts_retention");

                    b.HasIndex("OperationId", "AttemptNumber")
                        .IsUnique()
                        .HasDatabaseName("uq_provider_attempt_operation_number");

                    b.ToTable("provider_attempts", "snowshot", t =>
                        {
                            t.HasCheckConstraint("ck_provider_attempt_lifecycle", "(\"State\" = 0 AND \"DispatchState\" = 0 AND \"CompletedAt\" IS NULL AND \"Outcome\" IS NULL AND \"HttpStatus\" IS NULL AND \"InputUnits\" = 0 AND \"OutputUnits\" = 0 AND \"CostNanoYuan\" = 0 AND NOT \"CostKnown\") OR (\"State\" = 1 AND \"DispatchState\" IN (1, 2, 3) AND \"CompletedAt\" IS NOT NULL AND \"CompletedAt\" >= \"StartedAt\" AND \"Outcome\" IS NOT NULL AND (\"DispatchState\" <> 1 OR (\"CostKnown\" AND \"CostNanoYuan\" = 0)))");

                            t.HasCheckConstraint("ck_provider_attempt_state", "\"State\" IN (0, 1) AND \"DispatchState\" BETWEEN 0 AND 3");

                            t.HasCheckConstraint("ck_provider_attempt_values", "\"AttemptNumber\" > 0 AND \"InputUnits\" >= 0 AND \"OutputUnits\" >= 0 AND \"CostNanoYuan\" >= 0 AND (\"CostKnown\" OR \"CostNanoYuan\" = 0)");
                        });
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.UsageEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("CostKnown")
                        .HasColumnType("boolean");

                    b.Property<long>("InputUnits")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<long>("OperatorCostNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("OperatorOverageNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("OutputUnits")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<long>("PublicCostNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_usage_events_retention");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("uq_usage_events_operation");

                    b.ToTable("usage_events", "snowshot", t =>
                        {
                            t.HasCheckConstraint("ck_usage_event_values", "\"InputUnits\" >= 0 AND \"OutputUnits\" >= 0 AND \"PublicCostNanoYuan\" >= 0 AND \"OperatorCostNanoYuan\" >= 0 AND \"OperatorOverageNanoYuan\" >= 0");
                        });
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.UsageOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AbsoluteDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ActualOperatorNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("ActualPublicNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("AllowanceDate")
                        .HasColumnType("date");

                    b.Property<long>("AllowanceLimitNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Fence")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("IdempotencyHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<long>("InputRateNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("OperatorOverageNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("OutputRateNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("OwnerToken")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PolicyFingerprint")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<long>("PolicyRevision")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uuid");

                    b.Property<long>("ReservedOperatorNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservedPublicNanoYuan")
                        .HasColumnType("bigint");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("SettledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("SettlementFingerprint")
                        .HasMaxLength(32)
                        .HasColumnType("bytea");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyHash")
                        .IsUnique()
                        .HasDatabaseName("uq_usage_operations_idempotency_hash");

                    b.HasIndex("PrincipalId", "AllowanceDate")
                        .HasDatabaseName("ix_usage_operations_principal_period");

                    b.HasIndex("State", "LeaseExpiresAt")
                        .HasDatabaseName("ix_usage_operations_reconciliation");

                    b.HasIndex("State", "SettledAt")
                        .HasDatabaseName("ix_usage_operations_retention");

                    b.ToTable("usage_operations", "snowshot", t =>
                        {
                            t.HasCheckConstraint("ck_usage_operation_costs", "\"InputRateNanoYuan\" >= 0 AND \"OutputRateNanoYuan\" >= 0 AND \"ReservedPublicNanoYuan\" >= 0 AND \"ReservedOperatorNanoYuan\" >= 0 AND \"ActualPublicNanoYuan\" >= 0 AND \"ActualOperatorNanoYuan\" >= 0 AND \"OperatorOverageNanoYuan\" >= 0");

                            t.HasCheckConstraint("ck_usage_operation_deadline", "\"CreatedAt\" < \"AbsoluteDeadline\" AND \"LeaseExpiresAt\" <= \"AbsoluteDeadline\"");

                            t.HasCheckConstraint("ck_usage_operation_fence", "\"Fence\" > 0");

                            t.HasCheckConstraint("ck_usage_operation_hashes", "octet_length(\"IdempotencyHash\") = 32 AND octet_length(\"OwnerToken\") = 32 AND octet_length(\"PolicyFingerprint\") = 32 AND \"PolicyRevision\" > 0 AND (\"SettlementFingerprint\" IS NULL OR octet_length(\"SettlementFingerprint\") = 32)");

                            t.HasCheckConstraint("ck_usage_operation_kind", "\"Kind\" IN (0, 1, 2)");

                            t.HasCheckConstraint("ck_usage_operation_state", "\"State\" BETWEEN 0 AND 4");

                            t.HasCheckConstraint("ck_usage_operation_terminal", "(\"State\" IN (0, 1) AND \"SettledAt\" IS NULL AND \"SettlementFingerprint\" IS NULL) OR (\"State\" IN (2, 3, 4) AND \"SettledAt\" IS NOT NULL AND \"SettlementFingerprint\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.AllowancePeriodEntity", b =>
                {
                    b.HasOne("SnowShot.Infrastructure.Persistence.PrincipalEntity", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.PolicyStateEntity", b =>
                {
                    b.HasOne("SnowShot.Infrastructure.Persistence.PolicyRevisionEntity", null)
                        .WithMany()
                        .HasForeignKey("ActiveRevision")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.PrincipalFingerprintEntity", b =>
                {
                    b.HasOne("SnowShot.Infrastructure.Persistence.PrincipalEntity", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.ProviderAttemptEntity", b =>
                {
                    b.HasOne("SnowShot.Infrastructure.Persistence.UsageOperationEntity", null)
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.UsageEventEntity", b =>
                {
                    b.HasOne("SnowShot.Infrastructure.Persistence.UsageOperationEntity", null)
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SnowShot.Infrastructure.Persistence.UsageOperationEntity", b =>
                {
                    b.HasOne("SnowShot.Infrastructure.Persistence.PrincipalEntity", null)
                        .WithMany()
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
